apiVersion: v1
kind: Namespace
metadata:
  name: shards

---
apiVersion: v1
kind: Service
metadata:
  name: shards
  namespace: shards
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: shards

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shards-pvc
  namespace: shards
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shards
  name: shards
  namespace: shards
spec:
  selector:
    matchLabels:
      app: shards
  template:
    metadata:
      labels:
        app: shards
    spec:
      containers:
        - name: shards
          image: ghcr.io/damaged0ne/shards:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
          volumeMounts:
            - mountPath: /data
              name: shards-pv
      volumes:
        - name: shards-pv
          persistentVolumeClaim:
            claimName: shards-pvc
